baseURL = "http://example.org/"
languageCode = "zh-CN"
title = "jakiechen's blog"
theme = "maupassant"

[author]
  name = "jakiechen"

#GA
googleAnalytics = "UA-134507027-1"

#disqus
disqusShortname = "jakiechen"

#summary
summaryLength = 140

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"

[permalinks]
  posts = "/:year/:month/:title/"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 3

[params]
  author = "jakiechen"
  subtitle = "Tencent高级开发工程师，专注后台开发，高性能服务，C++，golang"
  description = "Tencent高级开发工程师，专注后台开发，高性能服务，C++，golang"
  keywords = ""
  busuanzi = true
  preserveTaxonmyNames = true
  disablePathToLower = true
  [[params.links]]
    title = "企鹅电竞"
    name = "企鹅电竞"
    url = "https://egame.qq.com"
  [[params.ads]]
    title = "todo..."
    url = "https://www.qq.com"
    img = ""
  [params.utteranc]
    enable = true
    repo = "xdjakiechen/utterance-repo"
    issueTerm = "pathname"
    theme = "github-light"

